### PR TITLE
Updates on the Gallery WebsiteNov 26

### PR DESCRIPTION
**Pull request by SlShannon**
Made additional changes on the Website

### CODE REVIEW

**Comment by SlShannon** [comment]
Given the container more height px within each gallery box

**Comment by nbriz** [comment]
hey @SlShannon 
so we never got a chance to finish the code refactoring that u started w/Ilai in class. but i just sent an email to the entire class w/a video tutorial to download (check ur email). in that tutorial, one of the things i cover is how to create that gallery (but w/simpler && cleaner CSS/HTML). watch the tutorial && update ur code so that it looks a bit more like the example in my tutorial

**Comment by SlShannon** [comment]
Thank you Nick, I made new html & css for the about page on the website.

**Comment by nbriz** [comment]
@SlShannon did u push ur changes? GitHub says ur last updates were 7 days ago

**Comment by SlShannon** [comment]
Hey Nick,

Yes I had made multiple commit, I will figure out why I am not able to push
up to git. I will take a better look at it tonight, because currently I am
at work.  The About page's HTML and CSS is done, the Home page HTML and CSS
code are cleaned and finished designing.

**Comment by nbriz** [comment]
ok, leave a comment here when u've pushed updates to ur repo (or let me know if u need help figuring out why it's not getting pushed). but one thing to try (if Atom is giving u trouble pushing) is pushing ur code up via the terminal:
1. `cd` into ur repo folder in the terminal
2. then run `git push origin master`

**Comment by nbriz** [comment]
@SlShannon it seems there's a merge conflict here (it's that dang .DS_Store), could u delete all .DS_Store files in ur repo, then commit && push again?

**Comment by SlShannon** [comment]
Hello Nick,

I tired to delete my .DS_Store, but it won't let me. The .DS_Store is
showing up in my Atom, but not in the folder files.

[image: Screen Shot 2019-12-04 at 8.39.50 PM.png]

**Comment by SlShannon** [comment]
Here is what my folder looks like

[image: Screen Shot 2019-12-04 at 8.45.21 PM.png]

**Comment by nbriz** [comment]
@SlShannon that's b/c it's a "hidden file", remember that any file that starts with a "." is a hidden file. Atom shows u all the hidden files by default, but finder does not. u can press "CMD + SHIFT + ." in ur finder to toggle show/hide the hidden files.

otherwise u could also delete them with the terminal:
- first `cd` into ur project folder
- then run `rm .DS_Store`
- && then `rm server/.DS_Store`

**Comment by SlShannon** [comment]
Hello Nick,

Yes, after I run the rm .DS_Store, I still have merge conflict.

[image: Screen Shot 2019-12-05 at 6.01.44 PM.png]
[image: Screen Shot 2019-12-05 at 5.59.01 PM.png]

**Comment by nbriz** [comment]
@SlShannon ok we need to try to resolve this soon b/c @harae37 is waiting on this merge before she can start working on her next part. let's see if we can get on a quick skype (or google hangouts) call sometime tomorrow (Friday) to figure this out. send me an email w/a time that works best for u

**Comment by SlShannon** [comment]
Hello Nick,

Yes I understand, I believe I have everything completed for the
server section, except the fact that I can't not merge my code within the
group. I am free after 6 pm tomorrow for google hangout, also I am free on
Saturday and Sunday before 2 pm to chat and solve this problem. Thank you
for all the help and patience.

Thank you,

Shannon

**Comment by nbriz** [comment]
@SlShannon ok let's meet tonight at 6:15, how's that sound? shouldn't take more than ~15mins

**Comment by SlShannon** [comment]
Hell Nick,

Are you available right now

**Pull request merged**
