### PR TITLE
Communicat between "popup.js" && "content.js" finish

### PR DESCRIPTION
**Pull request by zylemma**
I change the "background_scripts" filename to "content.js" to avoid confusion.
I think I figure out the communication between "popup.js" and "cotent.js", now every-time when the popup is open, the "popup.js" will ask "content.js" to check the status. And when press the "Run" button the "dataRecord" code will start to run. But I can't stop the "dataRecord" code when press "Stop" button, although I think I send message from "popup.js" to "content.js" successfully.

### CODE REVIEW

**Comment by zylemma** [comment]
@nbriz @Steve-luo Also I lookup Steve's code about the scroll, but it shows that when the mouse is not moving but only scrolling, the data cannot be record

**Comment by jluo98** [comment]
> @nbriz @Steve-luo Also I lookup Steve's code about the scroll, but it shows that when the mouse is not moving but only scrolling, the data cannot be record

There is no data recorded in-between scrolling, but my drawing code will link the two points to form a straight line. So wheel data is not needed, only the window position data is needed.

**Comment by nbriz** [comment]
@zylemma + @Steve-luo i just made a video answer this + other questions for u, i'm going to email it to u guys now (FYI: just like the last video i sent, this one might not have sound in Quicktime, so make sure to watch it in another media player like VLC or a u can also watch it in a browser like Firefox)

**Comment by nbriz** [comment]
@Steve-luo + @zylemma + @jwham92 i've merged Yuli's pull request, so u guys can fetch/merge && do the next part. it probably makes more sense that Jason implement his part before Jiwon does hers (but i leave that to u to decide)

**Pull request merged**
